dev:
  build: .
  volumes:
     - ./:/cinder
  working_dir: /cinder

robot:
  build: robot/
  volumes:
     - ./:/repo/
  working_dir: /repo/robot
  links:
    - server

docs:
  build: docs/
  volumes:
     - ./docs:/docs
  working_dir: /docs

client:
  build: .
  volumes:
     - ./:/cinder
  working_dir: /cinder/example/
  links:
    - redis
    - server
  environment:
    - PYTHONPATH=/cinder/
  command: python example.py

server:
  build: example/server
  volumes:
     - ./example/server:/server
  working_dir: /server
  ports:
    - "8000:8000"
  links:
    - db
  command: bash entrypoint.sh

redis:
  image: redis

db:
  image: postgres
